spring:
  security:
    user:
      name: alex
      password: alexpass
      roles: USER,ADMIN

security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      scope: READ,WRITE
    authorization:
      check-token-access: permitAll

logging:
  level:
    org:
      springframework:
        security:
          web: debug